name: devDeployCCApp
  
on:
  push:
    branches:
      DEVELOP
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo the 
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: echo the github repository
      run: echo "${{ github.repository }}"
    - name: echo the  workflow 
      run: echo "${{ github.workflow }}"
    - name: echo the workspace 
      run: echo "${{ github.workspace }}"
    - name: echo the action 
      run: echo "${{ github.action }}"
    - name: echo the event
      run: echo "${{ github.event }}"
    - name: echo the event name 
      run: echo "${{ github.event_name }}"
    - name: echo the  from branch
      run: echo "${{ github.head_ref }}"
    - name: echo the to branch
      run: echo "${{ github.base_ref }}"
